language: node_js
sudo: required
node_js:
  - "6"
cache:
  directories:
    - "node_modules"  
install:
  - npm install
script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "151250010"
  - git config user.email "851642452@qq.com"
  - git add .
  - git commit -m "Update Blogs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - BlogSource

env:
  global:
    - GH_REF: github.com/151250010/151250010.github.io.git

cache:
  directories:
    - "node_modules"